services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: barbershop
      POSTGRES_PASSWORD: Israel2025!
    volumes:
      - "./Backend/volumes_postgres:/var/lib/postgresql/data"
      - "./Backend/database/database_init.sql:/docker-entrypoint-initdb.d/database_init.sql"
    ports:
      - '5444:5432'
    networks: 
      - mynetwork
  
  backend:
    container_name: BarberAPI
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - '8000:80'
    networks: 
      - mynetwork

  frontend:
    container_name: miapp-nginx
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    
    ports:
      - "80:80"
    networks: 
      - mynetwork


networks:
  mynetwork:
    driver: bridge